name: Create Release on system.json Update

on:
  push:
    paths:
      - "system.json"

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Read version from system.json
        id: read_version
        run: |
          VERSION=$(jq -r '.version' system.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          body: "Automated release for version ${{ env.VERSION }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
